### ISSUE TITLE
Comments on "A Blockchain to Rule Them All"

### ISSUE THREAD

**Issue by vmx** [kolmoblocks/website#2]
I've read through the [A Blockchain to Rule Them All](http://kolmoblocks.org/documentation/whitepaper/#a-blockchain-to-rule-them-all) section and I'm not really sure I fully understand the point you're making.

>  As an example, Bitcoin blocks refer to other blocks with hex-encoded SHA-256, and git hashing function can be described by the following lambdablock:

Git objects are also using a simple SHA1 hash. If you store a (decompressed) Git object in your system, it will already contain the `commit <length>NUL` prefix. So you can just SHA1 hash that and won't need to do any additional work. One nice characteristic of Merkle DAGs is that you can verify the content with only knowing the hash function that was used.

> Now we can make the block have the original hash with just a little change to the hash function lambdablock:

If you do this, it's not really a Merkle DAG anymore. It's just a blob with a hash.

**Comment by dborzov** [comment]
I appreciate your comment and apologize for the delay with the response.

It looks like I did not outline it that well, but the core idea behind the mechanism discussed in that section is that the logic for what is considered a Merkle DAG directed edge hash within the data block and how to look up that hash can be specified just by linking to a kolmoblock with the algorithm for that. So you can integrate the git object tree by simply adding attributes to the header of the git objects with the pointers for kolmoblocks with parsers for what to identify as an SHA1 hash pointer.

The kolmoblock team had another insight recently. It occurred to us that we will be better off if we de-emphasize  all the blockchain-related applications of kolmoblocks. The way we see it, the value of kolmoblocks is in the possibility for it to become the foundation of the next generation of content-addressable networking protocols. Our goal should be to laser-focus on this opportunity.  

We now see blockchain integration applications as a bit of a distraction from that. As a result, we decided to take down that section of the wallpaper.

Also, the title "A Blockchain to Rule Them All" ended up sounding really cringy. Not proud of that.
